###
### Simplified flow file to test exit code behavior
### This will intentionally fail on PolicyChecks and DriftDetection stages
###

globalVariables:
  LB_BASE_DIR: "."
  LB_ENVIRONMENT: "DEV"
  LB_TEST_CHECKS: "${LB_TEST_CHECKS:-T}"
  LB_TEST_DRIFT: "${LB_TEST_DRIFT:-T}"
  CHECKS_REPORT: "Checks_${LB_ENVIRONMENT}.html"
  DRIFT_REPORT: "Diff_${LB_ENVIRONMENT}.html"
  DIFF_FILE: "Diff_${LB_ENVIRONMENT}.json"
  SNAPSHOT_FILE: "Snapshot_${LB_ENVIRONMENT}.json"

stages:
  Verify:
    actions:
      - type: liquibase
        command: connect

      - type: liquibase
        command: validate

      - type: liquibase
        command: status

  PolicyChecks:
    actions:
      # This will fail if no checks-settings.conf exists
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks show
        cmdArgs: { check-status: "enabled" }

      # This will fail if checks fail
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks run
        cmdArgs: { report-enabled: "true", report-path: "${LB_BASE_DIR}", report-name: "${CHECKS_REPORT}", checks-scope: "changelog, database", changeset-filter: "pending", auto-update: "on" }

  DriftDetection:
    actions:
      # This will fail if snapshot doesn't exist
      - type: liquibase
        if: "exists('${SNAPSHOT_FILE}', false) && ${LB_TEST_DRIFT} == 'T'"
        command: diff
        globalArgs: { outputfile: "${LB_BASE_DIR}/${DIFF_FILE}" }
        cmdArgs: { drift-severity: "1", report-enabled: "true", report-path: "${LB_BASE_DIR}", report-name: "${DRIFT_REPORT}", referenceURL: "offline:postgres?snapshot=${SNAPSHOT_FILE}", format: json }

  Deploy:
    actions:
      - type: liquibase
        command: update
        cmdArgs: { report-enabled: "false" }

endStage:
  actions:
    - type: liquibase
      command: history
