name: Test Liquibase Exit Codes

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-liquibase-433:
    name: Test Liquibase 4.33 (Expected to fail properly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Liquibase
        uses: jbennett-liquibase/Demo_Composites/actions/setup-liquibase@v1

      - name: Run Liquibase Flow (4.33)
        run: liquibase flow --flow-file=liquibase.flowfile.yaml
        env:
          LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
          LIQUIBASE_COMMAND_URL: "jdbc:h2:mem:test"
          LIQUIBASE_COMMAND_USERNAME: "sa"
          LIQUIBASE_COMMAND_PASSWORD: ""
          LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog.xml"

          LB_BASE_DIR: ./
          LB_ENVIRONMENT: DEV
          LB_TEST_CHECKS: "T"
          LB_TEST_DRIFT: "T"
          LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: issues
          LIQUIBASE_DBCLHISTORY_ENABLED: true
          LIQUIBASE_LOG_FILE: ./liquibase.dev.log.json
          LIQUIBASE_LOG_FORMAT: json_pretty
          LIQUIBASE_LOG_LEVEL: warning
          LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: false
          LIQUIBASE_REPORTS_OPEN: false
          LIQUIBASE_SEARCH_PATH: ./
          LIQUIBASE_SHOW_BANNER: false

  test-liquibase-500:
    name: Test Liquibase 5.0.0 (Exit code issue)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Liquibase
        uses: jbennett-liquibase/Demo_Composites/actions/setup-liquibase@v2

      - name: Run Liquibase Flow (5.0.0)
        run: liquibase flow --flow-file=liquibase.flowfile.yaml
        env:
          LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
          LIQUIBASE_COMMAND_URL: "jdbc:h2:mem:test"
          LIQUIBASE_COMMAND_USERNAME: "sa"
          LIQUIBASE_COMMAND_PASSWORD: ""
          LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog.xml"

          LB_BASE_DIR: ./
          LB_ENVIRONMENT: DEV
          LB_TEST_CHECKS: "T"
          LB_TEST_DRIFT: "T"
          LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: issues
          LIQUIBASE_DBCLHISTORY_ENABLED: true
          LIQUIBASE_LOG_FILE: ./liquibase.dev.log.json
          LIQUIBASE_LOG_FORMAT: json_pretty
          LIQUIBASE_LOG_LEVEL: warning
          LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: false
          LIQUIBASE_REPORTS_OPEN: false
          LIQUIBASE_SEARCH_PATH: ./
          LIQUIBASE_SHOW_BANNER: false